Repository DigitalExcellence/dex-backend, pull requests merged in 2020-11, with the labels that each got.

#297 Bugfix/highlight result missing dates
  API/Resources/HighlightResourceResult.cs
  CHANGELOG.md
Labels: bug, priority

#294 Feature/271-delete-redundant-files
  API/Controllers/FileController.cs
  API/Controllers/ProjectController.cs
  CHANGELOG.md
  Postman/dex.postman_collection.json
  Postman/local.postman_environment.json
  Postman/testimage2.png
Labels: requires review

#318 Feature/317 include collaborators project overview
  API/Controllers/ProjectController.cs
  API/Resources/ProjectResultResource.cs
  CHANGELOG.md
  Repositories.Tests/ProjectRepositoryTest.cs
  Repositories/ProjectRepository.cs
  Services.Tests/ProjectServiceTest.cs
  Services/Services/ProjectService.cs
Labels: priority
