Repository DigitalExcellence/dex-backend, pull requests merged in 2021-06, with the labels that each got.

#451 Performance testing workflow
  .github/workflows/PerformanceTests.yml
Labels: work in progress

#462 Feature/377 fontys gitlab datasource to wizard
  API/Controllers/WizardController.cs
  API/Extensions/DependencyInjectionExtensions.cs
  API/appsettingsapi.Development.json
  API/appsettingsapi.json
  CHANGELOG.md
  Services.Tests/ExternalDataProviders/DataProviderServiceTest.cs
  Services.Tests/ExternalDataProviders/FontysGitlabDataSourceAdaptee.cs
  Services.Tests/ExternalDataProviders/GitlabDataSourceAdapteeTest.cs
  Services/ExternalDataProviders/DataProviderAdapter.cs
  Services/ExternalDataProviders/DataProviderService.cs
  Services/ExternalDataProviders/FontysGitlabDataSourceAdaptee.cs
  Services/ExternalDataProviders/GithubDataSourceAdaptee.cs
  Services/ExternalDataProviders/GitlabDataSourceAdaptee.cs
  Services/ExternalDataProviders/Interfaces/IDataSourceAdaptee.cs
  Services/ExternalDataProviders/Interfaces/IPrivateDataSourceAdaptee.cs
  Services/ExternalDataProviders/Interfaces/IPublicDataSourceAdaptee.cs
  Services/ExternalDataProviders/JsFiddleDataSourceAdaptee.cs
Labels: requires review

#471 Added like sorting
  API/Controllers/ProjectController.cs
  API/Resources/ProjectFilterParamsResource.cs
  CHANGELOG.md
  Models/ProjectFilterParams.cs
  Services/Services/ProjectService.cs
Labels: requires development

#479 Draft: Feature/477 improve search bar
  API/Controllers/SearchController.cs
  CHANGELOG.md
  Repositories.Tests/ProjectRepositoryTest.cs
  Repositories/ProjectRepository.cs
  Services/Services/SearchService.cs
Labels: bug

#452 feat(semantic-release): add automated semantic release
  .github/workflows/semantic-release.yml
  .releaserc.json
  CONTRIBUTING.MD
Labels: governance, input wanted, requires review
